#sp: 
#  users-service:
#    users: "[]"

spring:
  application:
    name: item-service
    
#server:
#  port: 8001

  rabbitmq:
    host: 192.168.247.1
    port: 5672
    username: admin
    password: admin
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
  instance:
    prefir-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
---
spring:
  profiles: item1
  
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002